greetings = ("hello6/9")
firstname = ("ศักดิพัฒน์")
lastname = ("จักกะพาก")
age = ("17")
height = ("164")
weight = ("84")
วิชาที่ชอบ = ("อังกฤษ")
วิชาที่ไม่ชอบ =("คณิตศาสตร์")
อาชีพในฝัน =("เชฟ")
อาชีพในฝัน =("ปลาดิบ")
print(greetings)
print(firstname)
print(lastname)
print(age)
print(height)
print(weight)
print(วิชาที่ชอบ)
print(วิชาที่ไม่ชอบ)
print(อาชีพในฝัน)
print(อาชีพในฝัน)
# ศักดิพัฒน์ จักกะพาก เลขที่ 32 6/9